version: '3'
services:
  web:
    build: .
    ports:
      - 3000:3000
      - 3035:3035
    volumes:
      - .:/cookbook
    tty: true
    stdin_open: true
    container_name: treinadev
volumes: 
  cookbook:

